### ISSUE TITLE
Создать unit-test для класса "кэш"

### ISSUE THREAD

**Issue by Sviftel** [Sviftel/Analyser-TCP-RE#2]
Использовать библиотеку google-test

**Comment by evlinsky** [comment]
Создавать пакеты можно вручную (объекты класса Md5HashedPayload

**Comment by evlinsky** [comment]
Тесты:
1. на уровне Md5HashedPayload (неповторяющиеся пакеты)
2. на уровне Md5HashedPayload (повторяющиеся пакеты ---- два раза один и тот же набор)
3. реальный файл прогнать два раза
