### ISSUE TITLE
Провести эксперименты на реальных данных

### ISSUE THREAD

**Issue by evlinsky** [Sviftel/Analyser-TCP-RE#5]
1. Взять реальные большие логи
   http://wand.net.nz/wits/localisp/a/1/
   http://wand.net.nz/wits/localisp/a/2/
   http://wand.net.nz/wits/localisp/a/3/
2. Сделать реальные свои логи
3. для разных типов трафика (видео, музыка, страницы, загрузка больших файлов (дистриб убунту) NB: https
4. 3 сессии для каждого сайта (2 одинаковые, 1 другая)
5. залить их (?)
6. сохранить в текстовом файле информацию про каждый лог
7. Замерить Hit Rate
8. Замерить скороть (time из time.h)
9. Повторимость эксперимента (bash скрипты)

**Comment by Sviftel** [comment]
Для повторимости на url'ах: посмотреть Selenium.
